baseurl: "https://ubnetdef.org/"
languageCode: "en-us"
title: "UBNetDef"
theme: "ubnetdef_2016"
disableHugoGeneratorInject: true

menu:
  main:
    - Name: "about"
      Weight: 100
    - Name: "FAQ"
      Weight: 101
      URL: "/about/faq"
      Parent: "about"
    - Name: "Competition Team"
      Weight: 102
      URL: "/about/competition-team"
      Parent: "about"

    - Name: "courses"
      Weight: 200
    - Name: "Systems Security"
      Weight: 201
      URL: "/courses/syssec"
      Parent: "courses"
    - Name: "Network Security"
      Weight: 202
      URL: "/courses/netsec"
      Parent: "courses"
    - Name: "Security Development Program"
      Weight: 203
      URL: "/courses/secdev"
      Parent: "courses"
    - Name: "---"
      Weight: 250
      Parent: "courses"
    - Name: "Previous Courses"
      Weight: 251
      URL: "/archived_courses"
      Parent: "courses"

    - Name: "lectures"
      Weight: 300
      URL: "/lectures"

    - Name: "lockdown"
      Weight: 400
      URL: "https://lockdown.ubnetdef.org"

    - Name: "wiki"
      Weight: 500
      URL: "https://wiki.ubnetdef.org"
